[program:steamstorebd-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/steamwalletstore/artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/var/www/steamwalletstore
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/steamwalletstore/storage/logs/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600

[program:steamstorebd-scheduler]
process_name=%(program_name)s
command=php /var/www/steamwalletstore/artisan schedule:work
directory=/var/www/steamwalletstore
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/steamwalletstore/storage/logs/scheduler.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
